services:
  mongodb:
    image: mongo:7.0.5-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: horde
      MONGO_INITDB_ROOT_PASSWORD: MDB_PSWD
    command: --quiet --logpath /dev/null
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 60 1 --port 30002 --loglevel warning
    volumes:
      - redis:/data

  horde_server:
    # Requires access to Unreal Engine's image repository on GitHub
    image: ghcr.io/epicgames/horde-server:latest
    restart: unless-stopped
    environment:
      # Horde uses standard configuration from ASP.NET, allowing values to be set through env vars and files.
      # See https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/
      # To configure via config file, see the mounted directory and file ./data/server.json.
      # The env vars below are set as they're configured through Docker Compose
      Horde__HttpPort: 0
      Horde__Http2Port: 13342
      Horde__RedisConnectionConfig: redis:30002
      Horde__DatabaseConnectionString: mongodb://horde:MDB_PSWD@mongodb:27017/Horde?authSource=admin
    volumes:
      # Mount Horde's data directory to ./data for easy viewing and modifying
      # Once server has started, this directory is populated with default configuration files from the container
      - ./data:/app/Data:z

  nginx:
    image: nginx:latest
    restart: unless-stopped
    read_only: true
    container_name: horde_nginx
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:z
      - ./html/.well-known/acme-challenge:/var/acme-challenge:z
      # Permissions setup: permissive for public certs, restricted privatekey.
      # sudo chmod 755 -R /etc/letsencrypt/{live,archive}
      # sudo chmod 640 /etc/letsencrypt/archive/horde.ninepointeightgame.com/privkey1.pem
      # sudo chgrp linuxuser /etc/letsencrypt/archive/horde.ninepointeightgame.com/privkey1.pem
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - nginx_cache:/var/cache/nginx
      - nginx_pid:/var/run

# Provide persistence between container restarts for MongoDB, Redis and nginx
volumes:
  mongodb:
    driver: local
  redis:
    driver: local
  nginx_cache:
    driver: local
  nginx_pid:
    driver: local
